In [1]:
import pandas as pd

In [3]:
T = pd.read_csv('6FL.csv')

In [6]:
T.head()

,t,p,alt,KMF,diff,ax,ay,az,gx,gy,gz,roll,pitch,RAM,Launch,Apo,Land
0,76790,95036.38,539.46,539.61,NaN,1.53,-0.05,0.18,-39.25,5.51,36.00,-15.10,-82.88,513,1,0,0
1,76826,95043.32,538.69,539.60,-0.01,2.00,0.02,0.27,-16.80,6.42,16.62,5.29,-82.39,513,1,0,0
2,76862,95034.53,539.67,539.60,0.00,2.00,0.13,0.88,9.90,3.49,0.87,8.25,-65.97,513,1,0,0
3,76899,95037.71,539.18,539.60,0.00,2.00,0.13,0.29,8.87,23.78,-11.56,24.32,-80.93,513,1,0,0
4,76935,95036.00,539.43,539.60,0.00,2.00,0.06,0.22,29.72,42.08,-62.58,14.78,-83.37,513,1,0,0

In [14]:
if (T['diff'] <= -0.5):
    print('Pass 1')

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [19]:
T['diff'] <= -0.5

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
378    False
379    False
380    False
381    False
382    False
383    False
384    False
385    False
386    False
387    False
388    False
389    False
390    False
391    False
392    False
393    False
394    False
395    False
396    False
397    False
398    False
399    False
400    False
401    False
402    False
403    False
404    False
405    False
406    False
407    False
Name: diff, Length: 408, dtype: bool